### ISSUE TITLE
Update link to examples

### ISSUE THREAD

**Issue by ari-stotle-max** [pharmaverse/pharmaverse-pkg#2]
The examples page has been moved to : https://pharmaverse.github.io/examples/

**Comment by rossfarrugia** [comment]
@mstackhouse you ok to sort these minor issues? and then i can review/approve and merge, and we could push back a new version to CRAN if needed

**Comment by mstackhouse** [comment]
@rossfarrugia Update PR'd here: https://github.com/pharmaverse/pharmaverse-pkg/pull/3
